version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Frontend dependencies
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/functions"  # Firebase backend dependencies
    schedule:
      interval: "weekly"
